# MySQL. Versions 5.0 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: chat_app_management
  username: root
  password: 123123
  #socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default

test:
  <<: *default
  database: chat_app_test

production:
  <<: *default
